"""An English demo dataset for the README screenshots.

Writes synthetic Claude Code transcripts into a demo root, ingests them into a demo
database next to them and seeds telemetry and advice on top of the result. The real
~/.claude and ~/.local/share/cburn are never touched: `make demo` points the server at
the tree with CLAUDE_CONFIG_DIR, CBURN_CONFIG and CBURN_DATA_DIR.

Run:   .venv/bin/python tools/demo_data.py [--root DIR]
Serve: make demo (the script prints the env line as well)

`--tick` appends a fresh burst to the live sessions of an existing tree so the gauge
needle is up at the moment of a screenshot; the running server's watcher picks the
appended lines up within a second.
"""

from __future__ import annotations

import argparse
import json
import random
import shutil
import sys
import uuid
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from cburn import config, db, pricing  # noqa: E402
from cburn.collector.indexer import ingest_tree  # noqa: E402
from cburn.metrics import local_day_start  # noqa: E402

DEFAULT_ROOT = Path.home() / ".local" / "share" / "cburn-demo"

#: The marker that lets the script wipe and rebuild a directory: without it a mistyped
#: --root would delete something real.
MARKER = ".cburn-demo"

VERSION = "2.1.231"
HOME = "/Users/alex"

#: The demo instance reads this instead of the real config: its own port, the advisor
#: and telegram off (the seeded advice must not be overwritten by a real `claude -p`).
CONFIG_TOML = """\
# Generated by tools/demo_data.py - the config of the demo instance.

[server]
port = 8798

[analyzer]
enabled = false
language = "en"

[telegram]
mode = "off"

[otel]
enabled = true

[prices.claude-opus-5]
input = 5.0
output = 25.0
cache_write_5m = 6.25
cache_write_1h = 10.0
cache_read = 0.5

[prices.claude-sonnet-5]
input = 2.0
output = 10.0
cache_write_5m = 2.5
cache_write_1h = 4.0
cache_read = 0.2

[prices.claude-haiku-4-5]
input = 1.0
output = 5.0
cache_write_5m = 1.25
cache_write_1h = 2.0
cache_read = 0.1
"""

#: Bash commands per project - they survive normalisation and fill the tool profile.
BASH: dict[str, list[str]] = {
    "acme-storefront": [
        "npm test",
        "npx vitest run checkout",
        "npm run build",
        "npx tsc --noEmit",
        "git diff --stat",
        "git log --oneline -5",
    ],
    "billing-api": [
        "pytest -q",
        "pytest -q tests/test_webhooks.py",
        "ruff check .",
        "git status",
        "docker compose up -d",
    ],
    "infra": ["terraform plan", "terraform validate", "kubectl get pods -n staging", "git diff"],
    "data-pipeline": ["pytest -q", "python -m pipeline.backfill --dry-run", "git status"],
    "dotfiles": ["tmux source ~/.tmux.conf", "git diff", "brew list"],
}

#: Non-Bash tools with weights close to the real profile of an editing session.
TOOLS: list[tuple[str, int]] = [
    ("Read", 8),
    ("Edit", 6),
    ("Bash", 6),
    ("Grep", 3),
    ("Write", 2),
    ("Glob", 2),
    ("TodoWrite", 2),
    ("WebFetch", 1),
]


def _stamp(at: datetime) -> str:
    return f"{at:%Y-%m-%dT%H:%M:%S}.{at.microsecond // 1000:03d}Z"


class Transcript:
    """One JSONL transcript, written the way Claude Code 2.1.x writes it.

    Records accumulate with datetimes and are shifted as a whole on `write`, so a
    session is authored forward and then anchored by its last record ("ends 45 s ago").
    """

    def __init__(
        self,
        rng: random.Random,
        session_id: str,
        project: str,
        branch: str,
        model: str,
        entrypoint: str = "cli",
    ) -> None:
        self.rng = rng
        self.id = session_id
        self.project = project
        self.cwd = f"{HOME}/code/{project}"
        self.branch = branch
        self.model = model
        self.entrypoint = entrypoint
        self.records: list[tuple[datetime, dict[str, Any]]] = []
        self.bare: list[dict[str, Any]] = []  # title and last-prompt records carry no time
        self.last_uuid: str | None = None
        self.context = 0

    def _hex(self, length: int) -> str:
        return "".join(self.rng.choice("0123456789abcdef") for _ in range(length))

    def _uuid(self) -> str:
        return str(uuid.UUID(int=self.rng.getrandbits(128), version=4))

    def _record(self, at: datetime, body: dict[str, Any], sidechain: bool = False) -> None:
        record = {
            "parentUuid": self.last_uuid,
            "isSidechain": sidechain,
            "userType": "external",
            "entrypoint": self.entrypoint,
            "cwd": self.cwd,
            "sessionId": self.id,
            "version": VERSION,
            "gitBranch": self.branch,
            "uuid": self._uuid(),
            **body,
        }
        self.last_uuid = record["uuid"]
        self.records.append((at, record))

    def prompt(self, at: datetime, text: str, compact: bool = False) -> None:
        body: dict[str, Any] = {"type": "user", "message": {"role": "user", "content": text}}
        if compact:
            body["isCompactSummary"] = True
        self._record(at, body)

    def tool_result(self, at: datetime, tool_use_id: str, sidechain: bool = False) -> None:
        content = [{"tool_use_id": tool_use_id, "type": "tool_result", "content": "[result]"}]
        self._record(
            at, {"type": "user", "message": {"role": "user", "content": content}}, sidechain
        )

    def turn(
        self,
        at: datetime,
        output: int,
        tools: list[tuple[str, dict[str, Any]]] | None = None,
        sidechain: bool = False,
        model: str | None = None,
        read: int | None = None,
        write_1h: int = 0,
    ) -> list[str]:
        """One model answer: a text record plus a record per tool_use, identical usage."""
        if read is None:
            read = self.context
            if not self.context and not write_1h:
                write_1h = self.rng.randint(16_000, 22_000)  # first turn caches the system prompt
            write_5m = self.rng.randint(400, 3_500) if self.context else 0
            self.context = read + write_5m + write_1h + output
        else:
            write_5m = self.rng.randint(200, 1_200)  # a sidechain grows its own small context
        usage = {
            "input_tokens": self.rng.randint(2, 9),
            "cache_creation_input_tokens": write_5m + write_1h,
            "cache_read_input_tokens": read,
            "output_tokens": output,
            "service_tier": "standard",
            "cache_creation": {
                "ephemeral_5m_input_tokens": write_5m,
                "ephemeral_1h_input_tokens": write_1h,
            },
        }
        message_id = "msg_" + self._hex(24)
        request_id = "req_" + self._hex(24)
        blocks: list[dict[str, Any]] = [{"type": "text", "text": "[answer]"}]
        tool_ids: list[str] = []
        for name, tool_input in tools or []:
            tool_id = "toolu_" + self._hex(22)
            tool_ids.append(tool_id)
            blocks.append({"type": "tool_use", "id": tool_id, "name": name, "input": tool_input})
        for index, block in enumerate(blocks):
            message = {
                "model": model or self.model,
                "id": message_id,
                "type": "message",
                "role": "assistant",
                "content": [block],
                "stop_reason": "tool_use" if tool_ids else "end_turn",
                "stop_sequence": None,
                "usage": usage,
            }
            body = {"type": "assistant", "requestId": request_id, "message": message}
            self._record(at + timedelta(milliseconds=350 * index), body, sidechain)
        return tool_ids

    def pick_tool(self) -> tuple[str, dict[str, Any]]:
        name = self.rng.choices([n for n, _ in TOOLS], [w for _, w in TOOLS])[0]
        if name == "Bash":
            return name, {"command": self.rng.choice(BASH[self.project])}
        return name, {}

    def title(self, text: str) -> None:
        self.bare.append({"type": "ai-title", "aiTitle": text, "sessionId": self.id})

    def last_prompt(self, text: str) -> None:
        record = {"type": "last-prompt", "lastPrompt": text, "leafUuid": self.last_uuid}
        self.bare.append({**record, "sessionId": self.id})

    def path(self, root: Path) -> Path:
        slug = f"{HOME}/code/{self.project}".replace("/", "-")
        return root / "claude" / "projects" / slug / f"{self.id}.jsonl"

    def write(self, root: Path, end_at: datetime) -> None:
        """Anchor the session so its last record lands at `end_at`, then write the file."""
        shift = end_at - self.records[-1][0]
        path = self.path(root)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", encoding="utf-8") as fh:
            for at, record in self.records:
                fh.write(json.dumps({**record, "timestamp": _stamp(at + shift)}) + "\n")
            for record in self.bare:
                fh.write(json.dumps(record) + "\n")

    def append(self, root: Path) -> None:
        """Append the accumulated records as they are - the `--tick` path."""
        with self.path(root).open("a", encoding="utf-8") as fh:
            for at, record in self.records:
                fh.write(json.dumps({**record, "timestamp": _stamp(at)}) + "\n")


def build_session(tr: Transcript, spec: dict[str, Any]) -> str | None:
    """Author the whole conversation; return the pending tool_use id for a live tail."""
    rng = tr.rng
    at = datetime(2026, 1, 1, tzinfo=UTC)  # any base: `write` anchors by the last record
    hot = spec.get("live") == "working"
    for index, text in enumerate(spec["prompts"]):
        if index == spec.get("compact_at"):
            summary = "This session is being continued from a previous conversation..."
            tr.prompt(at, summary, compact=True)
            tr.context = 30_000  # the compaction collapses the context
            at += timedelta(seconds=rng.uniform(15, 40))
        tr.prompt(at, text)
        at += timedelta(seconds=rng.uniform(4, 10))
        idle = index in spec.get("idle_at", ())
        for _ in range(0 if idle else rng.randint(3, 6) if hot else rng.randint(2, 5)):
            ids = tr.turn(at, output=rng.randint(90, 700), tools=[tr.pick_tool()])
            at += timedelta(seconds=rng.uniform(2, 8) if hot else rng.uniform(3, 25))
            tr.tool_result(at, ids[0])
            at += timedelta(seconds=rng.uniform(1, 6))
        if index == spec.get("sidechain_at"):
            at = _sidechain(tr, at)
        tr.turn(at, output=rng.randint(4, 8) if idle else rng.randint(300, 2_200))
        at += timedelta(seconds=rng.uniform(15, 60) if hot else rng.uniform(25, 240))
    pending: str | None = None
    if spec.get("live") in ("working", "permission"):
        tr.prompt(at, spec["live_prompt"])
        at += timedelta(seconds=rng.uniform(4, 9))
        pending = tr.turn(
            at, output=rng.randint(100, 400), tools=[("Bash", {"command": spec["live_command"]})]
        )[0]
    tr.title(spec["title"])
    tr.last_prompt(spec["prompts"][-1] if not pending else spec["live_prompt"])
    return pending


def _sidechain(tr: Transcript, at: datetime) -> datetime:
    """A Task fan-out: a few haiku turns living in the parent file, marked isSidechain."""
    rng = tr.rng
    ids = tr.turn(at, output=rng.randint(100, 300), tools=[("Task", {})])
    at += timedelta(seconds=rng.uniform(2, 5))
    read = 8_000
    for _ in range(3):
        side = tr.turn(
            at,
            output=rng.randint(200, 900),
            tools=[("Grep", {})],
            sidechain=True,
            model="claude-haiku-4-5-20251001",
            read=read,
        )
        at += timedelta(seconds=rng.uniform(2, 6))
        tr.tool_result(at, side[0], sidechain=True)
        at += timedelta(seconds=rng.uniform(1, 4))
        read += rng.randint(2_000, 5_000)
    tr.tool_result(at, ids[0])
    return at + timedelta(seconds=rng.uniform(1, 4))


def hours(n: float) -> timedelta:
    return timedelta(hours=n)


def sessions_spec() -> list[dict[str, Any]]:
    """Thirteen sessions over three days; the three live ones cover the status palette."""
    return [
        {
            "project": "acme-storefront",
            "branch": "fix/checkout-rounding",
            "model": "claude-sonnet-5",
            "title": "Checkout rounding fix",
            "end": timedelta(seconds=8),
            "live": "working",
            "live_prompt": "run the full suite and fix whatever falls out",
            "live_command": "npx vitest run checkout",
            "entrypoint": "claude-vscode",
            "prompts": [
                "why is the order total off by a cent on carts that mix currencies?",
                "write a failing test for the EUR+USD cart first",
                "now fix the rounding - money math should stay in cents end to end",
                "same bug in the tax line, fix it the same way",
                "ok, looks good",
                "refactor: pull the cents helpers into money.ts and use them everywhere",
                "update the snapshot tests, they still assert the floating totals",
                "thanks",
                "add a regression test for the 0.1+0.2 classic while we are here",
                "check git log to see who introduced the float math, just curious",
            ],
            "idle_at": (4, 7),
        },
        {
            "project": "billing-api",
            "branch": "feat/webhook-retries",
            "model": "claude-sonnet-5",
            "title": "Idempotent webhook retries",
            "end": timedelta(seconds=170),
            "live": "permission",
            "live_prompt": "apply the migration to staging",
            "live_command": "alembic upgrade head",
            "prompts": [
                "stripe retries webhooks and we double-book invoices; make delivery idempotent",
                "store the event id, not a hash - stripe already guarantees uniqueness",
                "add a test where the same event lands twice within a second",
                "now the alembic migration for the dedupe table",
            ],
        },
        {
            "project": "infra",
            "branch": "main",
            "model": "claude-opus-5",
            "title": "Staging autoscaling policy",
            "end": timedelta(seconds=45),
            "live": "answered",
            "prompts": [
                "staging pods thrash between 2 and 10 replicas all night, look at the hpa",
                "set a stabilization window and a sane scale-down rate",
                "show me the final terraform plan output",
            ],
        },
        {
            "project": "acme-storefront",
            "branch": "feat/gift-cards",
            "model": "claude-sonnet-5",
            "title": "Gift card support",
            "end": hours(3.5),
            "compact_at": 6,
            "sidechain_at": 2,
            "idle_at": (8,),
            "prompts": [
                "add gift cards: a payment method with a balance, partial redemption allowed",
                "schema first - cards, redemptions, and an audit trail",
                "find every place that assumes a single payment method per order",
                "make checkout accept card + gift card in one order",
                "the balance must never go negative, add a constraint and a test",
                "wire the refund path: refunds go back to the gift card first",
                "now the admin screen: issue a card, void a card",
                "emails: send the recipient a card with a redeem link",
                "ok",
                "run the whole suite and clean up the failures",
            ],
        },
        {
            "project": "data-pipeline",
            "branch": "fix/backfill-dedupe",
            "model": "claude-haiku-4-5-20251001",
            "title": "Backfill dedupe",
            "end": hours(5),
            "prompts": [
                "the backfill inserts duplicate events when it is restarted, dedupe on event_id",
                "add a dry-run mode that only reports what it would insert",
                "run it against the staging dump",
            ],
        },
        {
            "project": "dotfiles",
            "branch": "main",
            "model": "claude-sonnet-5",
            "title": "Tmux statusline tweaks",
            "end": hours(7),
            "prompts": [
                "move the git branch into the tmux statusline, drop the hostname",
                "the colors are unreadable on the light terminal profile, fix both",
            ],
        },
        {
            "project": "acme-storefront",
            "branch": "feat/server-components",
            "model": "claude-opus-5",
            "title": "Product grid on server components",
            "end": hours(26),
            "sidechain_at": 1,
            "prompts": [
                "migrate the product grid to server components, keep the filters client-side",
                "audit which grid children actually use state",
                "move data fetching into the page, kill the useEffect waterfall",
                "the lighthouse numbers, before and after",
                "ship it",
            ],
        },
        {
            "project": "billing-api",
            "branch": "fix/invoice-pdf-timeouts",
            "model": "claude-sonnet-5",
            "title": "Invoice PDF timeouts",
            "end": hours(29),
            "prompts": [
                "invoice PDFs time out for customers with 200+ line items, profile it",
                "render the table in chunks instead of one giant flow",
                "add a regression test with a 500-line invoice",
            ],
        },
        {
            "project": "infra",
            "branch": "chore/tls-rotation",
            "model": "claude-sonnet-5",
            "title": "TLS cert rotation",
            "end": hours(31),
            "prompts": [
                "the staging certs expire in 12 days and nothing rotates them, wire cert-manager",
                "add an alert 20 days before expiry",
            ],
        },
        {
            "project": "data-pipeline",
            "branch": "feat/schema-versioning",
            "model": "claude-sonnet-5",
            "title": "Event schema versioning",
            "end": hours(34),
            "prompts": [
                "producers keep breaking consumers; version the event schemas",
                "a registry table plus a compatibility check in CI",
                "backfill the version column for the old events",
            ],
        },
        {
            "project": "acme-storefront",
            "branch": "fix/cart-a11y",
            "model": "claude-sonnet-5",
            "title": "Cart drawer accessibility",
            "end": hours(50),
            "prompts": [
                "the cart drawer traps neither focus nor escape, fix the a11y basics",
                "announce quantity changes to screen readers",
                "axe reports two more violations on the empty cart, clean them up",
            ],
        },
        {
            "project": "billing-api",
            "branch": "feat/rate-limiter",
            "model": "claude-opus-5",
            "title": "Per-tenant rate limiter",
            "end": hours(53),
            "prompts": [
                "one tenant can starve the API for everyone, add a per-tenant rate limit",
                "sliding window in redis, fail open if redis is down",
                "expose the remaining quota in the response headers",
                "load-test it with the seeded tenants",
            ],
        },
        {
            "project": "dotfiles",
            "branch": "main",
            "model": "claude-haiku-4-5-20251001",
            "title": "Zsh prompt migration",
            "end": hours(55),
            "prompts": [
                "move my prompt from oh-my-zsh to a bare zsh setup, keep the git segment",
                "startup got 300ms faster, verify with hyperfine",
            ],
        },
    ]


def generate(root: Path) -> None:
    if root.exists():
        if not (root / MARKER).exists():
            sys.exit(f"{root} exists and does not look like a demo root ({MARKER} missing)")
        shutil.rmtree(root)
    root.mkdir(parents=True)
    (root / "data").mkdir()
    (root / MARKER).touch()
    (root / "config.toml").write_text(CONFIG_TOML, encoding="utf-8")

    now = datetime.now(UTC)
    rng = random.Random(20260819)
    state: list[dict[str, Any]] = []
    sessions: list[tuple[dict[str, Any], Transcript]] = []
    for spec in sessions_spec():
        tr = Transcript(
            rng,
            str(uuid.UUID(int=rng.getrandbits(128), version=4)),
            spec["project"],
            spec["branch"],
            spec["model"],
            spec.get("entrypoint", "cli"),
        )
        pending = build_session(tr, spec)
        tr.write(root, now - spec["end"])
        sessions.append((spec, tr))
        if spec.get("live"):
            state.append(
                {
                    "kind": spec["live"],
                    "file": str(tr.path(root)),
                    "id": tr.id,
                    "project": spec["project"],
                    "cwd": tr.cwd,
                    "branch": tr.branch,
                    "model": tr.model,
                    "entrypoint": tr.entrypoint,
                    "last_uuid": tr.last_uuid,
                    "context": tr.context,
                    "pending_tool": pending,
                }
            )
    (root / "state.json").write_text(json.dumps(state, indent=2), encoding="utf-8")

    conn = db.connect(root / "data" / "cburn.db")
    try:
        pricing.sync_prices(conn, config.load(root / "config.toml"))
        ingest_tree(conn, root / "claude" / "projects")
        by_title = {spec["title"]: tr.id for spec, tr in sessions}
        with conn:
            seed_advice(conn, now, by_title)
            seed_otel(conn, now, rng, by_title)
        turns, cost = conn.execute("SELECT COUNT(*), SUM(cost_usd) FROM turns").fetchone()
        print(f"demo root: {root}")
        print(f"sessions: {len(sessions)}, turns: {turns}, cost: ${cost:.2f}")
    finally:
        conn.close()
    print("serve it with:")
    print(
        f"  CLAUDE_CONFIG_DIR={root}/claude CBURN_CONFIG={root}/config.toml"
        f" CBURN_DATA_DIR={root}/data .venv/bin/cburn serve"
    )


def seed_advice(conn: Any, now: datetime, by_title: dict[str, str]) -> None:
    """Two advisor runs: a fresh one with open tips and yesterday's, already answered."""
    gift = by_title["Gift card support"][:8]
    checkout = by_title["Checkout rounding fix"][:8]
    grid = by_title["Product grid on server components"][:8]

    def run(ts: datetime, severity: str, items: list[tuple[str, str, str, str, str, str]]) -> None:
        cursor = conn.execute(
            "INSERT INTO advice (ts, kind, period_start, period_end, model, cost_usd,"
            " max_severity, status) VALUES (?, 'hourly', ?, ?, 'haiku', ?, ?, 'new')",
            (
                _stamp(ts),
                _stamp(ts - timedelta(hours=24)),
                _stamp(ts),
                0.0041,
                severity,
            ),
        )
        for key, title, sev, detail, action, evidence, status in items:
            conn.execute(
                "INSERT INTO advice_items (advice_id, key, title, severity, detail, action,"
                " evidence, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (cursor.lastrowid, key, title, sev, detail, action, evidence, status),
            )

    run(
        now - timedelta(minutes=35),
        "warn",
        [
            (
                "cache-5m-churn",
                "Nearly half of today's cache writes expire unused",
                "warn",
                "The 5-minute cache is rewritten on almost every turn of the long sessions:"
                " the same context is paid for again after every pause longer than five minutes.",
                "Prefer the 1-hour cache for the stable context (system prompt, CLAUDE.md)"
                " and keep bursts of related edits inside one turn.",
                f"today: 4.1M tokens written to the 5m cache, 2.4M of them rewritten within"
                f" the hour; the heaviest run is session {gift}",
                "new",
            ),
            (
                "compact-152k",
                "A session hit 152k of context and auto-compacted",
                "warn",
                "After a compaction the model re-reads the summary at full price and part"
                " of the working thread is lost.",
                "Split long work into one session per feature; keep CLAUDE.md and the"
                " pinned files lean.",
                f"session {gift} compacted after 152k of context; the re-read that followed"
                f" cost $0.84",
                "new",
            ),
            (
                "manual-permissions",
                "16 manual permission confirmations today",
                "info",
                "Most of them approve the same two test commands, and every one stops the"
                " work until a human answers.",
                "Allowlist Bash(npm test:*) and Bash(pytest:*) in settings.json permissions.",
                f"tool_decision: Bash approved by hand 7 times (npm test, pytest -q) in"
                f" session {checkout}, Edit 6, WebFetch 3",
                "new",
            ),
        ],
    )
    run(
        now - timedelta(hours=25),
        "warn",
        [
            (
                "useeffect-waterfall",
                "A client-side fetch waterfall burns turns on re-reads",
                "warn",
                "The product grid refetched on every filter change, and each round trip"
                " came back through the model.",
                "Move the data fetching to the server component and pass the filters down.",
                f"session {grid}: 14 of 41 turns re-read the same three files",
                "accepted",
            ),
            (
                "haiku-for-greps",
                "Search fan-outs run on the top model",
                "info",
                "Grep-and-summarise subagents do not need the large model.",
                "Route Task subagents used for search to haiku.",
                f"session {grid}: 3 subagent runs, all on the session's main model",
                "rejected",
            ),
        ],
    )


def seed_otel(conn: Any, now: datetime, rng: random.Random, by_title: dict[str, str]) -> None:
    """Telemetry on top of the transcripts: what the JSONL alone cannot show.

    The main-work numbers mirror the ingested turns (a couple of per cent higher, as in
    life); the service spend, permission decisions, hooks and tool durations are the
    events the dashboard's "beyond the transcripts" widget and the session screen read.
    """
    day_start = local_day_start(now)
    sessions = list(by_title.values())

    def metric(name: str, ts: datetime, value: float, kind: str | None, **attrs: Any) -> None:
        conn.execute(
            "INSERT INTO otel_metrics (key, name, ts, session_id, model, kind, value, attrs)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (
                uuid.UUID(int=rng.getrandbits(128), version=4).hex,
                name,
                _stamp(ts),
                attrs.pop("session_id", rng.choice(sessions)),
                attrs.pop("model", None),
                kind,
                value,
                json.dumps(attrs),
            ),
        )

    def event(name: str, ts: datetime, **attrs: Any) -> None:
        conn.execute(
            "INSERT INTO otel_events (key, name, ts, session_id, attrs) VALUES (?, ?, ?, ?, ?)",
            (
                uuid.UUID(int=rng.getrandbits(128), version=4).hex,
                name,
                _stamp(ts),
                attrs.pop("session_id", rng.choice(sessions)),
                json.dumps(attrs),
            ),
        )

    def today(minutes_back_max: int = 480) -> datetime:
        at = now - timedelta(minutes=rng.uniform(2, minutes_back_max))
        return max(at, day_start)

    # The main work, mirrored from the ingested turns per model - telemetry sees a
    # couple of per cent more than the transcripts (service traffic rides along).
    rows = conn.execute(
        """
        SELECT model, SUM(input_tokens) AS inp, SUM(output_tokens) AS out,
               SUM(cache_read) AS red, SUM(cache_write_5m + cache_write_1h) AS wrt,
               SUM(cost_usd) AS cost
          FROM turns WHERE ts >= ? GROUP BY model
        """,
        (_stamp(day_start),),
    ).fetchall()
    for row in rows:
        for kind, value in (
            ("input", row["inp"]),
            ("output", row["out"]),
            ("cacheRead", row["red"]),
            ("cacheCreation", row["wrt"]),
        ):
            metric(
                "claude_code.token.usage",
                today(),
                round(value * 1.02),
                kind,
                model=row["model"],
                query_source="main",
            )
        metric(
            "claude_code.cost.usage",
            today(),
            row["cost"] * 1.02,
            None,
            model=row["model"],
            query_source="main",
        )

    # The service spend: session titles and SDK helpers - absent from the JSONL entirely.
    for _ in range(18):
        cost = rng.uniform(0.0004, 0.0009)
        event(
            "api_request",
            today(),
            query_source="generate_session_title",
            model="claude-haiku-4-5-20251001",
            cost_usd=round(cost, 6),
            duration_ms=rng.randint(600, 1_800),
        )
    for _ in range(8):
        event(
            "api_request",
            today(),
            query_source="sdk",
            model="claude-haiku-4-5-20251001",
            cost_usd=round(rng.uniform(0.01, 0.05), 6),
            duration_ms=rng.randint(2_000, 9_000),
        )
    for kind, value in (("input", 28_000), ("output", 5_200), ("cacheRead", 190_000)):
        metric(
            "claude_code.token.usage",
            today(),
            value,
            kind,
            model="claude-haiku-4-5-20251001",
            query_source="auxiliary",
        )
    metric(
        "claude_code.cost.usage",
        today(),
        0.24,
        None,
        model="claude-haiku-4-5-20251001",
        query_source="auxiliary",
    )

    # Permission decisions: mostly the config answers, a human confirms the rest by hand.
    manual = [
        ("Bash", "user_permanent", 7),
        ("Edit", "user_temporary", 6),
        ("WebFetch", "user_permanent", 3),
    ]
    for tool, source, count in manual:
        for _ in range(count):
            event("tool_decision", today(), tool_name=tool, source=source, decision="allow")
    for _ in range(2):
        event("tool_decision", today(), tool_name="Bash", source="user_reject", decision="reject")
    for _ in range(70):
        tool = rng.choice(["Read", "Edit", "Bash", "Grep", "Glob", "Write"])
        event("tool_decision", today(), tool_name=tool, source="config", decision="allow")
    for mode in ("acceptEdits", "acceptEdits", "plan"):
        event("permission_mode_changed", today(), to_mode=mode)

    # A few rate-limit retries: they cost time and never reach the transcript.
    for status in ("429", "429", "429", "529"):
        event("api_error", today(), status_code=status, model="claude-sonnet-5")

    # Hooks: fast tool guards and two slow HTTP ones on the prompt path.
    for hook, runs, low, high in (
        ("PreToolUse", 64, 4, 14),
        ("PostToolUse", 64, 3, 9),
        ("UserPromptSubmit", 18, 180, 650),
        ("Stop", 12, 300, 1_900),
    ):
        for _ in range(runs):
            event(
                "hook_execution_complete",
                today(),
                hook_event=hook,
                total_duration_ms=rng.randint(low, high),
                num_cancelled=0,
                num_non_blocking_error=0,
            )
        event("hook_registered", today(), hook_event=hook, hook_type="command")

    # What came out of the spend today.
    metric("claude_code.lines_of_code.count", today(), 1_284, "added")
    metric("claude_code.lines_of_code.count", today(), 402, "removed")
    metric("claude_code.active_time.total", today(), 4_620, "user")
    metric("claude_code.active_time.total", today(), 6_480, "cli")
    metric("claude_code.commit.count", today(), 11, None)

    # Tool durations for the gift-card session: the session screen shows time in tools.
    gift = by_title["Gift card support"]
    for tool, calls, low, high in (
        ("Bash", 21, 900, 41_000),
        ("Read", 34, 80, 600),
        ("Edit", 18, 90, 400),
        ("Grep", 12, 60, 500),
        ("WebFetch", 3, 2_000, 12_000),
    ):
        for _ in range(calls):
            event(
                "tool_result",
                now - timedelta(hours=rng.uniform(3.5, 4.6)),
                session_id=gift,
                tool_name=tool,
                duration_ms=rng.randint(low, high),
                success="true",
            )


FOLLOW_UPS = [
    "good, keep going",
    "now the edge cases",
    "run the tests again",
    "tighten the types while you are in there",
    "and the same fix on the admin side",
]


def tick(root: Path) -> None:
    """Append a fresh burst to the live sessions so the needle is up for a screenshot."""
    state_path = root / "state.json"
    if not state_path.exists():
        sys.exit(f"{state_path} missing - generate the dataset first")
    state = json.loads(state_path.read_text(encoding="utf-8"))
    now = datetime.now(UTC)
    rng = random.Random()
    for entry in state:
        if entry["kind"] == "permission":
            continue  # it hangs on purpose
        tr = Transcript(
            rng, entry["id"], entry["project"], entry["branch"], entry["model"], entry["entrypoint"]
        )
        tr.last_uuid = entry["last_uuid"]
        tr.context = entry["context"]
        if entry["kind"] == "working":
            at = now - timedelta(seconds=75)
            if entry.get("pending_tool"):
                tr.tool_result(at, entry["pending_tool"])
                at += timedelta(seconds=rng.uniform(2, 4))
            for _ in range(2):
                ids = tr.turn(at, output=rng.randint(150, 800), tools=[tr.pick_tool()])
                at += timedelta(seconds=rng.uniform(3, 8))
                tr.tool_result(at, ids[0])
                at += timedelta(seconds=rng.uniform(2, 5))
            tr.turn(at, output=rng.randint(400, 1_400))
            at += timedelta(seconds=rng.uniform(4, 8))
            tr.prompt(at, rng.choice(FOLLOW_UPS))
            pending = tr.turn(
                now - timedelta(seconds=3),
                output=rng.randint(100, 400),
                tools=[("Bash", {"command": rng.choice(BASH[entry["project"]])})],
            )
            entry["pending_tool"] = pending[0]
        else:  # answered: a fresh question, a fresh answer, still waiting for the human
            tr.prompt(now - timedelta(seconds=40), rng.choice(FOLLOW_UPS))
            tr.turn(now - timedelta(seconds=25), output=rng.randint(500, 1_500))
        tr.append(root)
        entry["last_uuid"] = tr.last_uuid
        entry["context"] = tr.context
    state_path.write_text(json.dumps(state, indent=2), encoding="utf-8")
    print("live sessions refreshed")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=DEFAULT_ROOT, help="demo root directory")
    parser.add_argument("--tick", action="store_true", help="refresh the live sessions only")
    args = parser.parse_args()
    if args.tick:
        tick(args.root)
    else:
        generate(args.root)


if __name__ == "__main__":
    main()
